### ISSUE TITLE
tvPlatformColor and tvPaneColor do not work

### ISSUE THREAD

**Issue by rockooor** [dextools-io/chart-widget#9]
Those parameters that are in the readme do not work. Try for example this:

https://www.dextools.io/widget-chart/en/avalanche/pe-light/0xbcabb94006400ed84c3699728d6ecbaa06665c89?theme=dark&chartType=1&chartResolution=30&headerColor=020618&tvColorPlatformBackground=020618&tvPaneColor=020618

The headerColor is changed but the other two aren't. I tried to search for something in the inspector, and it seems the querystring logic that's there for headerColor isn't there for the other two.

<img width="707" alt="image" src="https://github.com/dextools-io/chart-widget/assets/121937361/b67b83dd-8155-45d7-9f2d-8ebac055a0f2">

Thanks a lot!

**Comment by Dreamerryao** [comment]
same problem

**Comment by christophercr** [comment]
@rockooor @Dreamerryao the issue should be solved now. Could you please double check?

BTW, one of the query params in the example URL you gave is wrong, it should be `tvPlatformColor` instead of `tvColorPlatformBackground` :wink:

So, this would be the correct URL:
https://www.dextools.io/widget-chart/en/avalanche/pe-light/0xbcabb94006400ed84c3699728d6ecbaa06665c89?theme=dark&chartType=1&chartResolution=30&headerColor=020618&tvPlatformColor=020618&tvPaneColor=020618

**Comment by rockooor** [comment]
works! Thanks a lot for the quick fix :)

**Comment by christophercr** [comment]
Ah ok. Great! 😉
